### ISSUE TITLE
Create new `Window` class for `page.window_*` properties

### ISSUE THREAD

**Issue by ndonkoHenri** [flet-dev/flet#3414]
## Tasks
- [x] Create `Window` class and init in `Page`
- [x] Move `page.window_*` properties to `WIndow`
- [x] Deprecate `page.window_*` properties

## Idea/Goal
```py
# before
page.window_height

# after
page.window.height
```

**Comment by theAbdoSabbagh** [comment]
could u perhaps add a way to set the window icon? (titlebar icon)
